/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.1
 * Generated at: 2017-10-21 06:52:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.PrintWriter;

public final class Play_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Play</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Master.css\">\r\n");
      out.write("<script src=\"MasterWin.js\">\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"orange\" onload=\"loadImage();\">\r\n");
      out.write("\r\n");
      out.write("\t<section id=\"main\"> <canvas id=\"canvas\" width=\"900\"\r\n");
      out.write("\t\theight=\"600\"> Get Better ! </canvas> </section>\r\n");
      out.write("\r\n");
      out.write("\t");

char a[][] = new char[3][3];
a = (char[][])session.getAttribute("session_array"); 
int f=Integer.parseInt(session.getAttribute("flag").toString());
if(f==0)
{

      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("alert(\"oppps ! Try clicking a different location dude !\");\r\n");
      out.write("</script>\r\n");
      out.write("\t");

}

      out.write("\r\n");
      out.write("\t<!-- <div id=\"image\"><img src=\"Tic.jpg\"></div>\r\n");
      out.write(" -->\r\n");
      out.write("\t<form action=\"PlayGame\" method=\"get\">\r\n");
      out.write("\t\t<div id=\"tab\">\r\n");
      out.write("\t\t\t<table cellpadding=\"10\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th id=\"player\">Go</th>\r\n");
      out.write("\t\t\t\t\t<th id=\"player1\">");
      out.print(session.getAttribute("player_name"));
      out.write("</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" name=\"a\" value=\"1\">\r\n");
      out.write("\t\t\t\t\t\t\t");
if(a[0][0]=='X')
{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tdrawCross(1);\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t");
}if(a[0][0]=='0'){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tdrawCircle(1);\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" name=\"a\" value=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t");
if(a[0][1]=='X')
	{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tdrawCross(2);\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t");
}if(a[0][1]=='0'){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tdrawCircle(2);\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" name=\"a\" value=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t");
if(a[0][2]=='X')
	{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tdrawCross(3);\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t");
}if(a[0][2]=='0'){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tdrawCircle(3);\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" name=\"a\" value=\"4\">\r\n");
      out.write("\t\t\t\t\t\t\t");
if(a[1][0]=='X')
	{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tdrawCross(4);\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t");
}if(a[1][0]=='0'){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tdrawCircle(4);\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" name=\"a\" value=\"5\">\r\n");
      out.write("\t\t\t\t\t\t\t");
if(a[1][1]=='X')
	{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tdrawCross(5);\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t");
}if(a[1][1]=='0'){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tdrawCircle(5);\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" name=\"a\" value=\"6\">\r\n");
      out.write("\t\t\t\t\t\t\t");
if(a[1][2]=='X')
	{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tdrawCross(6);\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t");
}if(a[1][2]=='0'){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tdrawCircle(6);\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" name=\"a\" value=\"7\">\r\n");
      out.write("\t\t\t\t\t\t\t");
if(a[2][0]=='X')
	{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tdrawCross(7);\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t");
}if(a[2][0]=='0'){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tdrawCircle(7);\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" name=\"a\" value=\"8\">\r\n");
      out.write("\t\t\t\t\t\t\t");
if(a[2][1]=='X')
	{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tdrawCross(8);\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t");
}if(a[2][1]=='0'){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tdrawCircle(8);\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" name=\"a\" value=\"9\">\r\n");
      out.write("\t\t\t\t\t\t\t");
if(a[2][2]=='X')
	{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tdrawCross(9);\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t");
}if(a[2][2]=='0'){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tdrawCircle(9);\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
